# Generated by Django 2.0.9 on 2018-11-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rescatado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=10)),
                ('razaPredominante', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('foto', models.ImageField(upload_to='rescatados')),
            ],
        ),
    ]
