# Generated by Django 2.0.9 on 2018-11-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misperris', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescatado',
            name='foto',
            field=models.ImageField(upload_to=''),
        ),
    ]
