# Generated by Django 2.0.9 on 2018-11-12 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misperris', '0006_remove_perfil_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
