# Generated by Django 2.0.9 on 2018-11-13 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('misperris', '0007_delete_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=12)),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('region', models.CharField(max_length=50)),
                ('comuna', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=9)),
                ('tipoVivienda', models.CharField(choices=[('CASAPATIOGRANDE', 'Casa con patio grande'), ('CASAPATIOPEQUEÑO', 'Casa con patio pequeño'), ('CASASINPATIO', 'Casa sin patio'), ('DEPARTAMENTO', 'Departamento')], max_length=20, verbose_name='Tipo de Vivienda')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
