# Generated by Django 2.0.9 on 2018-11-13 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misperris', '0009_auto_20181112_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='comuna',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='fechaNacimiento',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='region',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='run',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipoVivienda',
            field=models.CharField(choices=[('CASAPATIOGRANDE', 'Casa con patio grande'), ('CASAPATIOPEQUEÑO', 'Casa con patio pequeño'), ('CASASINPATIO', 'Casa sin patio'), ('DEPARTAMENTO', 'Departamento')], max_length=20, verbose_name='Tipo de Vivienda'),
        ),
    ]
